### PR TITLE
Fix CMakeLists.txt

### PR DESCRIPTION
**Pull request by Dead-Deus**
Must be if statement

### CODE REVIEW

**Comment by MiguelMJ** [comment]
Just to understand the change: if you don't set the SFML_ROOT variable, CMake will search it; but if you set manually the SFML_ROOT variable, then no search will be performed, right? Isn't this the current behaviour?

**Comment by Dead-Deus** [comment]
No, it looks for SFML anyway, even if set (SFML_ROOT "") and cmake shows error
I think it`s because *find_package()* set SFML_FOUND to FALSE

*set(SFML_ROOT extlibs/SFML)*
```
1> [CMake] CMake Error at out/build/x64-Debug/extlibs/SFML/SFMLConfig.cmake:139 (message):
1> [CMake]   Requested SFML configuration (Shared) was not found
1> [CMake] Call Stack (most recent call first):
1> [CMake]   extlibs/Candle/CMakeLists.txt:17 (find_package)
1> [CMake] CMake Error at extlibs/Candle/CMakeLists.txt:17 (find_package):
1> [CMake]   Found package configuration file:
1> [CMake] 
1> [CMake]     C:/Users/Deus/Documents/Spark/out/build/x64-Debug/extlibs/SFML/SFMLConfig.cmake
1> [CMake] 
1> [CMake]   but it set SFML_FOUND to FALSE so package "SFML" is considered to be NOT
1> [CMake]   FOUND.
1> [CMake] 
1> [CMake] 
1> [CMake] -- Configuring incomplete, errors occurred!
```

**Comment by Dead-Deus** [comment]
My CMake
```
...
set(SFML_ROOT extlibs/SFML)
add_subdirectory(extlibs/Candle)
target_link_libraries(${PROJECT_NAME} PRIVATE Candle-s)

add_subdirectory(extlibs/SFML)
target_link_libraries(${PROJECT_NAME} PRIVATE sfml-system sfml-window sfml-graphics sfml-network)
...
```

**Comment by MiguelMJ** [comment]
Okey, then I'll merge the changes. Thanks once more for your contribution, Dead-Deus 😄

**Pull request merged**
